package com.example.MysqlAccess;

import java.sql.Timestamp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

//MVCクラスのコントローラ、ViewとModelの橋渡し
@Controller
public class MysqlAccessController {
	
	//他クラスの呼び出し
	@Autowired	// This means to get the bean called CustomerRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private CustomerRepository customerRepository;
	
	//employeeの定義
	@Autowired
	private EmployeeRepository employeeRepository;
	
	//departmentの定義
	@Autowired
	private DepartmentRepository departmentRepository;
	
	//クライアントからのリクエストに対してどのメソッドが処理を実行するか定義する
	//どんな場所か教えてくれる看板付きの入り口
	@RequestMapping("/")
    public String index() {
		// DBアクセスTop画面を表示
        return "index";
    }
	
	//GETの処理を行うプログラムの入り口、登録されているデータをとってきたりする。
	//list.htmlでで社員名簿一覧を表示
	@GetMapping(path="/all")
	public String list(Model model) {
		// M_CUSTOMERテーブルの全データを取得
		Iterable<Customer> customerList = customerRepository.findAll();
		
		// モデルに属性追加
		model.addAttribute("customerlist",customerList);

		// データ一覧画面を表示
		return "list";
	}
	
	//listEmployee.htmlで社員名簿一覧を表示
	@GetMapping(path="/allEmployee")
	public String listEmployee(Model model) {
		// M_EMPLOYEEテーブルの全データを取得
		Iterable<Employee> employeeList = employeeRepository.findAll();
		
		// モデルに属性追加
		model.addAttribute("employeelist",employeeList);

		// データ一覧画面を表示
		return "listEmployee";
	}
	
	//listDepartment.htmlで社員名簿一覧を表示
	@GetMapping(path="/allDepartment")
	public String listDepartment(Model model) {
		// M_EMPLOYEEテーブルの全データを取得
		Iterable<Department> departmentList = departmentRepository.findAll();
		
		// モデルに属性追加
		model.addAttribute("departmentlist",departmentList);

		// データ一覧画面を表示
		return "listDepartment";
	}
	
	//クライアントからのリクエストに対してどのメソッドが処理を実行するか定義する
	//どんな場所か教えてくれる看板付きの入り口
	//insert.htmlで顧客名簿のデータ登録画面を表示
	@RequestMapping("/insert")
    public String insert() {
		// データ登録画面を表示
        return "insert";
    }
	
	//insertEmployee.htmlで社員名簿のデータ登録画面を表示	
	@RequestMapping("/insertEmployee")
    public String insertEmployee() {
		// データ登録画面を表示
        return "insertEmployee";
    }
	
	//insertDepartment.htmlで社員名簿のデータ登録画面を表示
	@RequestMapping("/insertDepartment")
    public String insertDepartment() {
		// データ登録画面を表示
        return "insertDepartment";
    }
	
	//POSTの処理を行うプログラムの入り口。統合の役割を果たし、新しいデータを登録する
	// DB登録処理
	@PostMapping(path="/register")
	
	//メソッドに@ResponseBodyを付けると戻り値で直接レスポンスのコンテンツを返す事ができる。
	public @ResponseBody String addNewCustomer(	  @RequestParam String c_num 
												, @RequestParam String c_name
												, @RequestParam String address
												, @RequestParam String tel
												) {
		
		//customeraddDataインスタンスの作成
		Customer customerAddData = new Customer();
		
		//setAllメソッドを呼び出す
		customerAddData.setAll(c_num,c_name,address,tel);
		
		//timestampインスタンスの作成
		Timestamp timestamp = new Timestamp(System.currentTimeMillis()); //このメソッドはミリ秒単位の精度で現在時刻を知らせる。
		
		//それぞれのメソッドを呼び出す
		customerAddData.setCreate_date(timestamp);
		customerAddData.setCreate_user("auto_system");
		customerAddData.setUpdate_date(timestamp);
		customerAddData.setUpdate_user("auto_system");
		
		//保管場所のcustomerRepositpryにcustomerAddDataを保存
		customerRepository.save(customerAddData);
		
		return "登録しました";
	}
	

		@PostMapping(path="/registerEmployee")
		public @ResponseBody String addNewEmployee(	  @RequestParam String e_num 
													, @RequestParam String e_name
													, @RequestParam int e_year
													, @RequestParam String depart_cd
													) {
			
			Employee employeeAddData = new Employee();
			employeeAddData.setAll(e_num,e_name,e_year,depart_cd);
			
			Timestamp timestamp = new Timestamp(System.currentTimeMillis());
			employeeAddData.setCreate_date(timestamp);
			employeeAddData.setCreate_user("auto_system");
			employeeAddData.setUpdate_date(timestamp);
			employeeAddData.setUpdate_user("auto_system");
			
			employeeRepository.save(employeeAddData);
			
			return "登録しました";
		}
	
		@PostMapping(path="/registerDepartment")
		public @ResponseBody String addNewDepartment( @RequestParam String d_cd 
													, @RequestParam String d_name
													) {
			
			Department departmentAddData = new Department();
			departmentAddData.setAll(d_cd,d_name);
			
			Timestamp timestamp = new Timestamp(System.currentTimeMillis());
			departmentAddData.setCreate_date(timestamp);
			departmentAddData.setCreate_user("auto_system");
			departmentAddData.setUpdate_date(timestamp);
			departmentAddData.setUpdate_user("auto_system");
			
			departmentRepository.save(departmentAddData);
			
			return "登録しました";
		}

	
	
}
